spring.application.name=transaction-api
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:${KAFKA_PORT:9092}}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.properties[enable.idempotence]=true
spring.kafka.producer.properties[spring.json.add.type.headers]=false
spring.kafka.producer.properties[max.block.ms]=5000
spring.kafka.producer.properties[request.timeout.ms]=3000
spring.kafka.producer.properties[delivery.timeout.ms]=5000
payments.kafka.received-topic=transactions.received
payments.kafka.publish-timeout=10s
